"""Build the list words that are evidence of another language on their own.

Rewrites ``_FOREIGN_WORDS`` in ``laya/lang.py`` and ``laya-ts/src/foreign-words.ts``: every word
of the non-English stopword lists in ``laya/lang.py`` that occurs in none of the English documents
below. Those are the train splits of four public English corpora, at pinned revisions; their
test splits are where the rule's English cost is measured, so they are not read here.

A word is read the way ``laya.lang`` reads one: a run of letters, lowercased. A list word that
English text does use (``do``, ``van``, ``per``) still needs a second, different one beside it.

Usage::

    pip install datasets
    python scripts/build_foreign_words.py           # download (cached by `datasets`), write
    python scripts/build_foreign_words.py --check   # exit 1 if the files differ

Run it after changing a list. Until then a new word is not in the set, so it needs a second
word like any other: the safe side for English.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
import textwrap

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PY_OUT = os.path.join(REPO, "laya", "lang.py")
# The set's body in laya/lang.py; everything around it is hand-written and left alone.
PY_BLOCK = re.compile(r'(\n_FOREIGN_WORDS = frozenset\("""\n).*?(""".split\(\)\)\n)', re.S)
TS_OUT = os.path.join(REPO, "laya-ts", "src", "foreign-words.ts")

# (dataset, config, revision, text column), train split of each.
SOURCES = [
    ("clinc/clinc_oos", "plus", "155b9c710419136e17307b80d0a13e68cd46b4ec", "text"),
    ("mteb/banking77", None, "18072d2685ea682290f7b8924d94c62acc19c0b2", "text"),
    ("stanfordnlp/sst2", None, "8d51e7e4887a4caaa95b3fbebbf53c0490b58bbb", "sentence"),
    ("fancyzhx/ag_news", None, "eb185aade064a813bc0b7f42de02595523103ca4", "text"),
]


def english_vocabulary(word_re):
    from datasets import load_dataset

    seen, docs = set(), 0
    for name, config, revision, column in SOURCES:
        for text in load_dataset(name, config, split="train", revision=revision)[column]:
            seen.update(w.lower() for w in word_re.findall(text))
            docs += 1
    return seen, docs


def render_python(words, current):
    body = textwrap.fill(" ".join(words), width=96, initial_indent="    ", subsequent_indent="    ")
    out, n = PY_BLOCK.subn(lambda m: m.group(1) + body + "\n" + m.group(2), current)
    if n != 1:
        raise SystemExit("laya/lang.py: no `_FOREIGN_WORDS = frozenset(\"\"\"` block to rewrite")
    return out


def render_ts(words, docs):
    body = textwrap.fill(" ".join(words), width=96)
    return """/** Function words of other languages that English text does not use.
 *
 * Generated by `scripts/build_foreign_words.py`; do not edit by hand. Same words as `_FOREIGN_WORDS`
 * in `laya/lang.py`: the words of the non-English lists found in none of {docs:,} English documents.
 * {n} words.
 */
export const FOREIGN_WORDS: ReadonlySet<string> = new Set(`
{body}
`.split(/\\s+/).filter((w) => w.length > 0));
""".format(docs=docs, n=len(words), body=body)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="compare instead of writing")
    args = ap.parse_args(argv)

    sys.path.insert(0, REPO)
    from laya.lang import _OTHER_WORDS, _WORD

    seen, docs = english_vocabulary(_WORD)
    words = sorted(_OTHER_WORDS - seen)
    stale = []
    for path in (PY_OUT, TS_OUT):
        current = ""
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                current = f.read()
        text = render_python(words, current) if path == PY_OUT else render_ts(words, docs)
        if current != text:
            stale.append(os.path.relpath(path, REPO))
            if not args.check:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(text)
    print(f"{len(words)} of {len(_OTHER_WORDS)} list words occur in none of {docs:,} English documents")
    if args.check and stale:
        print("out of date: " + ", ".join(stale), file=sys.stderr)
        return 1
    if not args.check:
        print("rewrote: " + (", ".join(stale) or "nothing, already current"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
