/** Function words of other languages that English text does not use.
 *
 * Generated by `scripts/build_foreign_words.py`; do not edit by hand. Same words as `_FOREIGN_WORDS`
 * in `laya/lang.py`: the words of the non-English lists found in none of 212,592 English documents.
 * 841 words.
 */
export const FOREIGN_WORDS: ReadonlySet<string> = new Set(`
abar abbiamo aceasta această acest acesta acolo acum adakah adesso agora aici ainda ajke akan
akhon ako aku algo alguem alguém alla alle alors alsjeblieft alstublieft amader amake amma amra
ancaq anche ancora apakah apnake apnar apnara apni appen aqui aquí arep artiq artıq asbe
asseblief astazi atau aterbetala aterbetalning até auch auf aunque avete awak azi baada babagan
bado bagaimana bakal behover behöver belum berapa berapakah besok bhai bhalo bien bij bila
bilakah bir bisa bisakah bitte ble blivit boleh bolte bolun bukan bukas bydd cadê cand cati
chaina chdi ciao cine como consigo cuando daardie dadi dagli daha dalam dalla dallo dapat
dapatkah dari daripada dat ddim debiterade deg degli dello dengan denne depois dere deres despre
dessa detta dette deu deux deve devo devono deyil deze dhateng dheweke dhonnobad dich diese
diesen dieser dieses dilam dimana dimanakah diolch dir disse dite diye diyechi dois doit donc
donde dorkar duibar dupa după durung də efo eger ei eich ein eine einen einer eisiau eita ekbar
ekhon ekhono ekta elles endi entao então esok esta estamos estava esto estou está etta etter
että faktura fara fel ferot ficou fiz foarte foi fois fost fra från fue fueron fyddai får før
für fără gaan gallu gan ganger gani geche geen gelem gese gibt già gli gostaria graag gyda gyfer
gång gånger gör göra görə habe haben hadde haluaisin haluan hanen hanya hapa hapana harus havde
heb hebt heddiw heeft hefyd heidän hemos hendak hende hendes heute hierdie hii hij hingga hittar
hivi hiyo hizi hjalp hjalpa hjälp hjälpa hobe hocche hoeveel hoise hoje hoye hoyeche hoyni hulle
huomenna huu hva hvad hvala hvem hvilke hvilken hvilket hvor hvordan hvorfor hvornaar hvornår
hwn hyn hän hänen här həm hər iawn ich ieri ik ikaw iki ikke iku ile ili ilə imorgen ingin ini
installningarna installningen inställningarna inställningen inte isio isso isto isə iti iyan
iyon jabe jaz jeg jer jeres jetzt jij jika jodi joku jonno jotain jours jouw juga julle jutri jy
já kabeh kabla kaikki kailan kaj kako kalau kalian kaliyan kalke kama kami kamu kanggo kann
kannst kanthi kapan karena karo katera kateri katero katika kdaj kdo kenapa kenen keno kepada
kepiye kerana kesho ketika keu kharap khub kibhabe kichu kiitos kila kintu kita kivabe kje
kokhon koliko kommer korbo korchi kore koreche korechi korlam korsi korte korun kothay koto kowe
kraschar kuhusu kuinka kuka kula kulo kuna kunne kutoka kuwi kvittot kwa kwamba kwenye lagbe
lagi lakin lakini lebih lini losenord lui luwih lösenord maar mahu mais mana manakah maneh masih
mau mayroon mboten meget meidän meine meinem meinen meiner mellem mellom menawa mengapa menika
menyang mereka mes meu meus mihin mij mijn miksi mikä milloin mimi mina minha minhas minua
minulle minun minä missa missä mista mistä mita miten mitä moddhe mois moj moja moje molto muito
mung mutta mye myos myös más måste môre mən naar nach nai nama naman namin nang nanging nani nao
naomba nar nataka natin nawr naš ndani ndiyo necesito negli nei nekaj nel nella neng nenhum
nenhuma neu ngapi ngayon nggih nhw nicht nie niet nila ninataka ning ninguem ninguém nini niya
niye nje njegov njen noch noen nog nogen noget noite nossa nosso nous nya nyinyi não nämä när
nästa nå når nə obrigada obrigado och också od oder oggi ogsaa også oi olan oleh oli olmasa olub
olá ond onde onek oni onko onlar ontem onze oor opo oppnar ora ovat paano pabo pada paini paket
paki pakiusap paling paljonko pamoja panjenengan parben parbo parchi parchina pela pelo pengin
pentru perche peux peyechi pira piye più plis poate pob poco pode podem por porque poti pourquoi
preciso prosim pryd puede pueden punika punya pwy până quand quando quero questa questo quiero
rhaid rhywbeth roedd saan saat sahaja saja saka saking samo sampai sampeyan sampun sangat sapa
sathe saya scusa sebelum sedaj sedang sekali sekarang semasa sempre semua semula sesudah sesuk
setelah shathe shob shomossa siapa siapakah sich siella siellä sila silakan sina sini sinua
sinulle sinun sinä sisi siya siz skal skicka skulle smo sobre soko somossa sono sonra sparningen
spårningen stato ste sua sudah sul sulla sulle sunt sut sydd são säger să sən taalla tader
tafadhali tahole takk tama taman tambem também tanaan tapi tarde tayo teidän telah tena tengo
tenho tentang tetapi theke tidak tiene tienen tolong tomar tomra tous toute trebuie très três
tudi tudo tulung tumi tuo tva tvoj tvoja två tá tämä tämän tänään täällä ucun uga ugi uit unde
unrhyw untuk upp uppdaterats utawa utawi valo vandag var vas vaš ved venligst vennligst veut
veux vill vipi voces você vocês voglio voisitko voitko voor vores vorrei vous vrea vreau vse vya
våre vă və waar waarom wae wakati wala wangu wann wanneer wao wapi wedi welche werden wewe wij
wir wird worden wordt wrth wurde yake yako yalniz yalnız yangu ydy yeye yfory yma yn yna yote
yox yoxdur yw zaidi zakaj zal zdaj zij zijn zum zur är återbetala återbetalning çox è é être în
öppnar üçün če și ți əgər
`.split(/\s+/).filter((w) => w.length > 0));
