/** Function words of other languages that English text does not use.
 *
 * Generated by `scripts/build_foreign_words.py`; do not edit by hand. Same words as `_FOREIGN_WORDS`
 * in `laya/lang.py`: the words of the non-English lists found in none of 212,592 English documents.
 * 568 words.
 */
export const FOREIGN_WORDS: ReadonlySet<string> = new Set(`
abar abbiamo aceasta această acest acesta acum adakah adesso agora ainda ajke akan akhon ako aku
algo alguem alguém alla alle alors amader amake amma amra ancaq anche ancora apakah apnake apnar
apnara apni appen aqui aquí arep artiq artıq asbe asseblief atau aterbetala aterbetalning até
auch auf aunque avete awak bado bagaimana bakal behover behöver belum berapa besok bhai bhalo
bien bila bir bisa bitte ble blivit boleh bolte bolun bukan bukas bydd cadê chaina ciao como
consigo cuando daardie dagli daha dalam dalla dallo dapat dari dat ddim debiterade degli dello
dengan depois dessa detta deu deux deve devo devono deyil deze dheweke dhonnobad dich diese
diesen dieser dieses dilam dimana dir dite diye diyechi dois doit donc donde dorkar duibar după
durung də efo eger ei eich ein eine einen einer eita ekbar ekhon ekhono ekta elles endi entao
então esok esta estamos estava esto estou está faktura fel ferot ficou fiz foarte foi fois fost
fra från fue fueron får für fără gaan gan ganger geche gelem gese gibt già gli gostaria gyda
gång gånger gör göra görə habe haben harus heddiw hefyd hemos hendak heute hierdie hii hittar
hiyo hizi hjalp hjalpa hjälp hjälpa hobe hocche hoeveel hoise hoje hoye hoyeche hoyni hulle huu
här həm hər ich ieri ikaw iki iku ile ilə ingin ini installningarna installningen
inställningarna inställningen inte isso isto isə iyan iyon jabe jetzt jika jodi jonno jours juga
julle jy já kabeh kailan kalau kalke kama kami kamu kanggo kann kannst kapan karena karo katika
keno kepiye kerana kesho keu kharap khub kibhabe kichu kila kintu kita kivabe kokhon kommer
korbo korchi kore koreche korechi korlam korsi korte korun kothay koto kowe kraschar kuwi
kvittot kwa kwamba lagbe lagi lakin lakini lini losenord lui lösenord maar mahu mais mana maneh
mau mayroon meine meinem meinen meiner menyang mereka mes meu meus mimi minha minhas moddhe mois
molto muito mung más måste môre mən naar nach nai naman namin nang nanging nani nao nar natin
nawr necesito negli nel nella neng nenhum nenhuma neu ngapi ngayon nhw nicht nie niet nila ning
ninguem ninguém nini niya niye noch nog noite nossa nosso nous nya nyinyi não när nästa nə
obrigada obrigado och också oder oggi oi olan oleh olmasa olub olá ond onde onek onlar ontem oor
oppnar ora paano pabo pada paini paket paki pakiusap parben parbo parchi parchina pela pelo
pentru perche peux peyechi pira piye più poco pode podem por porque pourquoi preciso pryd puede
pueden pwy până quand quando quero questa questo quiero roedd saan sahaja saja saka sampeyan
sapa sathe saya scusa sedang sekarang sempre semua sesuk shathe shob shomossa siapa sich sila
sisi siya siz skicka skulle sobre somossa sono sonra sparningen spårningen stato sua sudah sul
sulla sulle sunt sut são säger să sən tader tafadhali tahole tambem também tapi tarde tayo telah
tena tengo tenho tetapi theke tidak tiene tienen tolong tomar tomra tous toute trebuie très três
tudo tulung tumi tuo tva två tá ucun uga uit untuk upp uppdaterats utawa valo vandag var veut
veux vill vipi voces você vocês voglio voor vorrei vous vreau vă və waar wae wala wann wanneer
wao wapi welche werden wewe wir wird worden wordt wrth wurde yalniz yalnız ydy yeye yfory yn
yote yox yoxdur yw zijn zum zur är återbetala återbetalning çox è é être în öppnar üçün și ți
əgər
`.split(/\s+/).filter((w) => w.length > 0));
